# Generated by Django 4.0.4 on 2022-05-31 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcastsearcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='podcastsearcher.podcast'),
            preserve_default=False,
        ),
    ]
